export const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';

export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';