export const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';

export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';

export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';

export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST';
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS';

export const ADD_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';